Overrides: use `lib.fakeHash` for unknown cryptography versions
When `null` hash is used, a cryptic error is printed for unknown
versions:

> unpacking source archive
> do not know how to unpack source archive

With fakeHash, the build continues and we can see an actual hash
mismatch error:

> error: hash mismatch in fixed-output derivation '/nix/store/m95mjg0rf1w1x6qrxby4dajy3shvn2r9-cryptography-37.0.4-vendor.tar.gz.drv':
>          specified: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
>             got:    sha256-f8r6QclTwkgK20CNe9i65ZOqvSUeDc4Emv6BFBhh1hI=